# Python `numpy` Module: Methods, Functions, and Examples

This notebook provides detailed notes, explanations, and examples for working with Python's `numpy` library. Each cell covers a specific concept or function.

## Introduction to `numpy`

`numpy` is a powerful Python library for numerical computing, providing support for arrays, mathematical functions, and linear algebra operations.

## Importing `numpy`

To use `numpy`, you need to import it. The convention is to use `import numpy as np`.

In [ ]:
import numpy as np

## Creating Arrays

The core of `numpy` is the `ndarray` object. You can create arrays using `np.array()` and other functions like `np.zeros()`, `np.ones()`, and `np.arange()`.

In [2]:
# Create arrays
arr1 = np.array([1, 2, 3])
arr2 = np.zeros((2, 3))
arr3 = np.ones(4)
arr4 = np.arange(0, 10, 2)
print('Array:', arr1)
print('Zeros:', arr2)
print('Ones:', arr3)
print('Arange:', arr4)

Array: [1 2 3]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [1. 1. 1. 1.]
Arange: [0 2 4 6 8]


## Array Attributes

`numpy` arrays have useful attributes like `shape`, `dtype`, and `size` to inspect their properties.

In [3]:
# Array attributes
print('Shape:', arr2.shape)
print('Data type:', arr1.dtype)
print('Size:', arr3.size)

Shape: (2, 3)
Data type: int64
Size: 4


## Array Indexing and Slicing

You can access and modify elements in arrays using indexing and slicing, similar to Python lists.

In [4]:
# Indexing and slicing
print('First element:', arr1[0])
print('Slice:', arr4[1:4])
arr1[1] = 10
print('Modified array:', arr1)

First element: 1
Slice: [2 4 6]
Modified array: [ 1 10  3]


## Array Operations

`numpy` supports element-wise operations, broadcasting, and mathematical functions like `np.sum()`, `np.mean()`, and `np.max()`.

In [5]:
# Array operations
arr5 = np.array([1, 2, 3, 4])
print('Sum:', np.sum(arr5))
print('Mean:', np.mean(arr5))
print('Max:', np.max(arr5))
print('Element-wise multiplication:', arr5 * 2)

Sum: 10
Mean: 2.5
Max: 4
Element-wise multiplication: [2 4 6 8]


## Reshaping and Transposing Arrays

You can change the shape of arrays using `reshape()` and transpose them using `T`.

In [6]:
# Reshape and transpose
arr6 = np.arange(6).reshape((2, 3))
print('Reshaped array:\n', arr6)
print('Transposed array:\n', arr6.T)

Reshaped array:
 [[0 1 2]
 [3 4 5]]
Transposed array:
 [[0 3]
 [1 4]
 [2 5]]


## Random Numbers with `numpy`

Use `np.random` methods to generate random numbers and arrays, such as `np.random.rand()` and `np.random.randint()`.

In [7]:
# Random numbers
rand_arr = np.random.rand(2, 2)
rand_ints = np.random.randint(0, 10, size=5)
print('Random array:\n', rand_arr)
print('Random integers:', rand_ints)

Random array:
 [[0.44096294 0.42544313]
 [0.67022615 0.13111639]]
Random integers: [6 1 5 9 6]


## Linear Algebra Functions

`numpy` provides linear algebra functions such as `np.dot()` for matrix multiplication and `np.linalg.inv()` for matrix inversion.

In [8]:
# Linear algebra
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print('Matrix multiplication:\n', np.dot(mat1, mat2))
print('Matrix inverse:\n', np.linalg.inv(mat1))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Summary

- `numpy` is essential for scientific computing in Python.
- Key features: arrays, mathematical functions, random numbers, and linear algebra.
- Explore more in the [NumPy documentation](https://numpy.org/doc/).

Let me know if you want to add advanced topics or specific examples!